In [134]:
import pandas as pd
import numpy as np


def get_min_max_avg(Train_Path_List,Test_Path_List): #train and test
    Outputs_Train = pd.DataFrame()
    Outputs_Test = pd.DataFrame()
    for Train_Path,Test_Path in zip(Train_Path_List, Test_Path_List):
        Train = pd.read_csv(Train_Path)
        Test  = pd.read_csv(Test_Path)
        Train = Train.iloc[:,:-1]
        Test = Test.iloc[:,:-1]
        Outputs_Train = pd.concat([Outputs_Train,Train])
        Outputs_Test = pd.concat([Outputs_Test,Test])
        break
    return [Outputs_Train.min(),Outputs_Train.max(),Outputs_Train.sum()/(Outputs_Train.shape[0]),Outputs_Train.std()], [Outputs_Test.min(),Outputs_Test.max(),Outputs_Test.sum()/(Outputs_Test.shape[0]), Outputs_Test.std()]
#return_list = [] // min, max, average

In [135]:



#name= all_data.col
#Name= ['Index','Hours','Julian Day','Week Day','Temperature','SR','p','Prec','RH','WD','WS']
Names = ['min', 'max', 'avg', 'std']
data_path= 'C:\\data\\PeakConcentration-Idea2-2-Clasification\\FullDay_Peak_Values\\'
Train_Path_List = [data_path+'NO2_Train.csv',data_path+'CO_Train.csv',data_path+'O3_Train.csv',data_path+'PM2_5_Train.csv', data_path+'SO2_Train.csv']
Test_Path_List = [data_path+'NO2_Test.csv', data_path+'CO_Test.csv', data_path+'O3_Test.csv', data_path+'PM2_5_Test.csv', data_path+'SO2_Test.csv']
Train_, Test_ = get_min_max_avg(Train_Path_List, Test_Path_List)

df1 = pd.DataFrame(Train_)
df1.insert(0, 'measurements_train', Names)
df2 = pd.DataFrame(Test_)
df2.insert(0, 'measurements_test', Names)

with open('statistic.csv','a') as f:
    f.write("Training Data")
    df1.to_csv(f, index=False)
    #f.write("\n")
    f.write("Testing Data")
    df2.to_csv(f, index=False)

print("Done to file statistic.csv")

Done to file statistic.csv

In [136]:
df1

,measurements_train,Index,Hours,Julian_day,Week_day,T_°C,SR_W/m2,p_mb,Prec_mm,RH_%,WD_°,WS_m/s
0,min,1.000000,0.000000,1.000000,0.000000,7.260000,0.000000,718.360000,0.000000,16.180000,0.000000,0.030000
1,max,35061.000000,23.000000,366.000000,6.000000,22.400000,1165.510000,729.930000,30.700000,99.580000,359.980000,4.880000
2,avg,17481.893103,12.236552,182.874483,3.000000,14.277212,162.725922,725.014205,0.200326,68.026826,164.583950,1.555251
3,std,10111.935728,6.466133,105.371437,1.996893,2.638539,245.682617,2.134353,1.287609,17.272811,89.975726,0.823956

In [137]:
df2

,measurements_test,Index,Hours,Julian_day,Week_day,T_°C,SR_W/m2,p_mb,Prec_mm,RH_%,WD_°,WS_m/s
0,min,35066.000000,0.000000,1.000000,0.000000,8.030000,0.000000,721.050000,0.000000,21.760000,0.12000,0.080000
1,max,43823.000000,23.000000,365.000000,6.000000,22.730000,1088.790000,730.750000,8.200000,98.980000,359.99000,4.620000
2,avg,39445.404110,12.404110,183.000000,2.991781,14.005123,172.200725,726.105854,0.110896,68.085279,159.30366,1.274803
3,std,2530.779499,6.594651,105.438271,2.004778,2.536091,252.903928,1.305673,0.620934,16.665618,94.84377,0.763752